services:
  # delivery-ms:
  # build: .
  # container_name: delivery-ms
  # ports:
  #   - 9000:9000
  # # depends_on:
  # #   - postgres
  # command: /greedygame

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${DL_MS_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DL_MS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DL_MS_POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DL_MS_POSTGRES_PORT}:${DL_MS_POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data:rw

volumes:
  database:
    driver: local
