// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.27.1
// source: deliverypb/deliverypb.proto

package deliverypb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	mi := &file_deliverypb_deliverypb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliverypb_deliverypb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_deliverypb_deliverypb_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *DeliveryRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *DeliveryRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type DeliveryResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Cta           string                 `protobuf:"bytes,3,opt,name=cta,proto3" json:"cta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponseItem) Reset() {
	*x = DeliveryResponseItem{}
	mi := &file_deliverypb_deliverypb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponseItem) ProtoMessage() {}

func (x *DeliveryResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_deliverypb_deliverypb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponseItem.ProtoReflect.Descriptor instead.
func (*DeliveryResponseItem) Descriptor() ([]byte, []int) {
	return file_deliverypb_deliverypb_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryResponseItem) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *DeliveryResponseItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeliveryResponseItem) GetCta() string {
	if x != nil {
		return x.Cta
	}
	return ""
}

type DeliveryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*DeliveryResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	mi := &file_deliverypb_deliverypb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliverypb_deliverypb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_deliverypb_deliverypb_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryResponse) GetItems() []*DeliveryResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_deliverypb_deliverypb_proto protoreflect.FileDescriptor

var file_deliverypb_deliverypb_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x22, 0x50, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x32, 0x6a, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x12, 0x5e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12,
	0x1b, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x42, 0x2d, 0x5a, 0x2b, 0x73, 0x65, 0x72, 0x69, 0x6f, 0x75, 0x73, 0x70, 0x6f, 0x6f, 0x70, 0x2f,
	0x67, 0x72, 0x65, 0x65, 0x64, 0x79, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deliverypb_deliverypb_proto_rawDescOnce sync.Once
	file_deliverypb_deliverypb_proto_rawDescData = file_deliverypb_deliverypb_proto_rawDesc
)

func file_deliverypb_deliverypb_proto_rawDescGZIP() []byte {
	file_deliverypb_deliverypb_proto_rawDescOnce.Do(func() {
		file_deliverypb_deliverypb_proto_rawDescData = protoimpl.X.CompressGZIP(file_deliverypb_deliverypb_proto_rawDescData)
	})
	return file_deliverypb_deliverypb_proto_rawDescData
}

var file_deliverypb_deliverypb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deliverypb_deliverypb_proto_goTypes = []any{
	(*DeliveryRequest)(nil),      // 0: deliverypb.DeliveryRequest
	(*DeliveryResponseItem)(nil), // 1: deliverypb.DeliveryResponseItem
	(*DeliveryResponse)(nil),     // 2: deliverypb.DeliveryResponse
}
var file_deliverypb_deliverypb_proto_depIdxs = []int32{
	1, // 0: deliverypb.DeliveryResponse.items:type_name -> deliverypb.DeliveryResponseItem
	0, // 1: deliverypb.Delivery.GetDelivery:input_type -> deliverypb.DeliveryRequest
	2, // 2: deliverypb.Delivery.GetDelivery:output_type -> deliverypb.DeliveryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deliverypb_deliverypb_proto_init() }
func file_deliverypb_deliverypb_proto_init() {
	if File_deliverypb_deliverypb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deliverypb_deliverypb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deliverypb_deliverypb_proto_goTypes,
		DependencyIndexes: file_deliverypb_deliverypb_proto_depIdxs,
		MessageInfos:      file_deliverypb_deliverypb_proto_msgTypes,
	}.Build()
	File_deliverypb_deliverypb_proto = out.File
	file_deliverypb_deliverypb_proto_rawDesc = nil
	file_deliverypb_deliverypb_proto_goTypes = nil
	file_deliverypb_deliverypb_proto_depIdxs = nil
}
